### ISSUE TITLE
Multiple File Conversion

### ISSUE THREAD

**Issue by ioridev** [HugoMcPhee/hdr-to-babylon-env#1]
npx github:HugoMcPhee/hdr-to-babylon-env

found
[ '2.hdr', '4.hdr', '3.hdr', '1.hdr' ]
converting to env files with a size of 256
/Users/iori/.npm/_npx/96a36878c0830435/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:208
            this._callbacks.set(id, { resolve, reject, error: new Error(), method });
                                                              ^

Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at /Users/iori/.npm/_npx/96a36878c0830435/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/iori/.npm/_npx/96a36878c0830435/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:207:16)
    at ExecutionContext._evaluateInternal (/Users/iori/.npm/_npx/96a36878c0830435/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:201:50)
    at ExecutionContext.evaluate (/Users/iori/.npm/_npx/96a36878c0830435/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:27)
    at DOMWorld.evaluate (/Users/iori/.npm/_npx/96a36878c0830435/node_modules/puppeteer-core/lib/cjs/puppeteer/common/DOMWorld.js:91:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

I want to convert all the multiple files in a folder

**Comment by HugoMcPhee** [comment]
Hi just saw your message 😅,
Hm it should support multiple files, wondering if the numbered filenames could be causing an issue? 

I haven't seen this error before 🤔,
I've also only tested it on windows
